Homework 6
================
Yike Zhao

This is my solution to HW6.

``` r
library(tidyverse)
```

    ## ── Attaching packages ────────────────────────────────────────────────────────────────────────────── tidyverse 1.3.0 ──

    ## ✓ ggplot2 3.3.2     ✓ purrr   0.3.4
    ## ✓ tibble  3.0.3     ✓ dplyr   1.0.2
    ## ✓ tidyr   1.1.2     ✓ stringr 1.4.0
    ## ✓ readr   1.4.0     ✓ forcats 0.5.0

    ## ── Conflicts ───────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(modelr)
library(dplyr)
```

## Problem 1

``` r
homicide_df = 
  read_csv("data/homicide-data.csv", na = c("", "NA", "Unknown")) %>% 
  mutate(
    city_state = str_c(city, state, sep = ", "),
    victim_age = as.numeric(victim_age),
    resolution = case_when(
      disposition == "Closed without arrest" ~ 0,
      disposition == "Open/No arrest"        ~ 0,
      disposition == "Closed by arrest"      ~ 1)
  ) %>% 
  filter(
    victim_race %in% c("White", "Black"),
    city_state != "Tulsa, AL") %>% 
  select(city_state, resolution, victim_age, victim_race, victim_sex)
```

    ## 
    ## ── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────
    ## cols(
    ##   uid = col_character(),
    ##   reported_date = col_double(),
    ##   victim_last = col_character(),
    ##   victim_first = col_character(),
    ##   victim_race = col_character(),
    ##   victim_age = col_double(),
    ##   victim_sex = col_character(),
    ##   city = col_character(),
    ##   state = col_character(),
    ##   lat = col_double(),
    ##   lon = col_double(),
    ##   disposition = col_character()
    ## )

Start with one city.

``` r
baltimore_df =
  homicide_df %>% 
  filter(city_state == "Baltimore, MD")
glm(resolution ~ victim_age + victim_race + victim_sex, 
    data = baltimore_df,
    family = binomial()) %>% 
  broom::tidy() %>% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(term, OR, starts_with("CI")) %>% 
  knitr::kable(digits = 3)
```

| term              |    OR | CI\_lower | CI\_upper |
| :---------------- | ----: | --------: | --------: |
| (Intercept)       | 1.363 |     0.975 |     1.907 |
| victim\_age       | 0.993 |     0.987 |     1.000 |
| victim\_raceWhite | 2.320 |     1.648 |     3.268 |
| victim\_sexMale   | 0.426 |     0.325 |     0.558 |

Try this across cities.

``` r
models_results_df = 
  homicide_df %>% 
  nest(data = -city_state) %>% 
  mutate(
    models = 
      map(.x = data, ~glm(resolution ~ victim_age + victim_race + victim_sex, data = .x, family = binomial())),
    results = map(models, broom::tidy)
  ) %>% 
  select(city_state, results) %>% 
  unnest(results) %>% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(city_state, term, OR, starts_with("CI")) 
```

``` r
models_results_df %>% 
  filter(term == "victim_sexMale") %>% 
  mutate(city_state = fct_reorder(city_state, OR)) %>% 
  ggplot(aes(x = city_state, y = OR)) + 
  geom_point() + 
  geom_errorbar(aes(ymin = CI_lower, ymax = CI_upper)) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

![](p8105_hw6_yz3738_files/figure-gfm/unnamed-chunk-5-1.png)<!-- -->

## Problem 2

``` r
baby_df = 
  read_csv("./data/birthweight.csv") %>% 
  mutate(
    babysex = as.factor(case_when(
      babysex == 1 ~ "male",
      babysex == 2 ~ "female")
    )
  )
```

    ## 
    ## ── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────
    ## cols(
    ##   .default = col_double()
    ## )
    ## ℹ Use `spec()` for the full column specifications.

For my model, I’d like to asses the relationship between mother’s BMI,
age at delivery, weights gained during pregnancy and child birth weight.
It’s reasonable to think that mother’s physical condition during
pregnancy and delivery would have certain influence on the child.

``` r
model_1 = lm(bwt ~ momage + ppbmi + wtgain, data=baby_df)

baby_df %>% 
  modelr::add_residuals(model_1) %>% 
  modelr::add_predictions(model_1) %>% 
  ggplot(aes(x=pred, y=resid)) + 
  geom_point()
```

![](p8105_hw6_yz3738_files/figure-gfm/unnamed-chunk-7-1.png)<!-- -->

Fit the two other model.

``` r
model_2 = lm(bwt ~ blength + gaweeks + wtgain, data=baby_df)
model_3 = lm(bwt ~ bhead*blength*babysex, data=baby_df)
```

Cross validation.

``` r
cv_df =
  crossv_mc(baby_df, 100) %>% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))
```

``` r
cv_df = 
  cv_df %>% 
  mutate(
    model_1 = map(train, ~lm(bwt ~ momage + ppbmi + wtgain, data = .x)),
    model_2 = map(train, ~lm(bwt ~ blength + gaweeks + wtgain, data = .x)),
    model_3 = map(train, ~lm(bwt ~ bhead*blength*babysex, data = .x))
    ) %>% 
  mutate(
    rmse_model_1 = map2_dbl(model_1, test, ~rmse(model = .x, data = .y)),
    rmse_model_2 = map2_dbl(model_2, test, ~rmse(model = .x, data = .y)),
    rmse_model_3 = map2_dbl(model_3, test, ~rmse(model = .x, data = .y))
    )
```

``` r
cv_df %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_violin()
```

![](p8105_hw6_yz3738_files/figure-gfm/unnamed-chunk-11-1.png)<!-- -->

Through cross validation, we can see that the model 3 with the
interactions of head circumference, length, sex has the best prediction
accuracy, while the model 1 I constructed has the least accuracy among
the three models.

## Problem 3

``` r
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

    ## Registered S3 method overwritten by 'hoardr':
    ##   method           from
    ##   print.cache_info httr

    ## using cached file: /Users/zao1ke/Library/Caches/R/noaa_ghcnd/USW00094728.dly

    ## date created (size, mb): 2020-12-09 09:31:17 (7.536)

    ## file min/max dates: 1869-01-01 / 2020-12-31

Bootstrap r-squared

``` r
r_df = weather_df %>% 
  modelr::bootstrap(n=5000) %>% 
  mutate(
    models = map(strap, ~lm(tmax ~ tmin, data = .x)),
    results = map(models, broom::glance)
  ) %>% 
  unnest(results) %>% 
  select(r.squared)
```

Plot distribution of r-squared and calculate 95% CI.

``` r
r_df %>%  
  ggplot(aes(x = r.squared)) + 
  geom_density()
```

![](p8105_hw6_yz3738_files/figure-gfm/unnamed-chunk-14-1.png)<!-- -->

``` r
r_df$r.squared %>% 
  quantile(probs =c(0.025, 0.975)) 
```

    ##      2.5%     97.5% 
    ## 0.8940051 0.9270491

The distribution of r-squared has a heavier tail extending to lower
values and a shoulder. The 95% CI of r-squared is (0.89, 0.93)

Bootstrap beta

``` r
beta_df = weather_df %>%
  modelr::bootstrap(n=5000) %>% 
  mutate(
    models = map(strap, ~lm(tmax ~ tmin, data = .x)),
    results = map(models, broom::tidy)
  ) %>% 
  unnest(results) %>% 
  select(.id, term, estimate) %>% 
  pivot_wider(
    names_from = "term",
    values_from = "estimate"
  ) %>% 
  janitor::clean_names() %>% 
  mutate(
    log_beta0beta1 = log(intercept*tmin)
  ) 
```

Plot distribution of r-squared and calculate 95% CI.

``` r
beta_df %>%  
  ggplot(aes(x = log_beta0beta1)) + 
  geom_density()
```

![](p8105_hw6_yz3738_files/figure-gfm/unnamed-chunk-17-1.png)<!-- -->

``` r
beta_df$log_beta0beta1 %>% 
  quantile(probs =c(0.025, 0.975)) 
```

    ##     2.5%    97.5% 
    ## 1.965413 2.057737

The distribution of log(beta0 \* beta1) has a heavier tail extending to
lower values. The 95% CI of log(beta0 \* beta1) is (1.97, 2.06)
